-- MySQL Script generated by MySQL Workbench
-- 07/13/17 20:41:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Observapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Observapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Observapp` DEFAULT CHARACTER SET utf8 ;
USE `Observapp` ;

-- -----------------------------------------------------
-- Table `Observapp`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`institucion` (
  `idinstitucion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(80) NOT NULL,
  `correo` VARCHAR(40) NOT NULL,
  `fono` VARCHAR(12) NOT NULL,
  `comuna` VARCHAR(45) NULL,
  `avatar_pat` MEDIUMTEXT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idinstitucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `username` VARCHAR(10) NULL,
  `tipo` INT(1) UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fnac` DATE NULL,
  `gender` VARCHAR(1) NULL,
  `avatar_pat` VARCHAR(300) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`observatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`observatorio` (
  `idobservatorio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idinst` INT UNSIGNED NOT NULL,
  `idmonitor` INT(11) NOT NULL,
  `max` INT NOT NULL,
  `avatar_pat` MEDIUMTEXT NULL,
  `nom` VARCHAR(45) NULL,
  `fecha` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idobservatorio`),
  UNIQUE INDEX `idobservatorio_UNIQUE` (`idobservatorio` ASC),
  INDEX `fk_observatorio_institucion_idx` (`idinst` ASC),
  INDEX `fk_observatorio_user1_idx` (`idmonitor` ASC),
  CONSTRAINT `fk_observatorio_institucion`
    FOREIGN KEY (`idinst`)
    REFERENCES `Observapp`.`institucion` (`idinstitucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observatorio_user1`
    FOREIGN KEY (`idmonitor`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`post` (
  `idpost` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `iduser` INT(11) NOT NULL,
  `tipo` INT UNSIGNED NOT NULL,
  `t_principal` VARCHAR(300) NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  `contenido` MEDIUMTEXT NULL,
  `tags` VARCHAR(320) NULL,
  INDEX `fk_post_user1_idx` (`iduser` ASC),
  PRIMARY KEY (`idpost`),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`ciudadano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`ciudadano` (
  `idobs` INT UNSIGNED NOT NULL,
  `iduser` INT(11) NOT NULL,
  INDEX `fk_ciudadano_observatorio1_idx` (`idobs` ASC),
  INDEX `fk_ciudadano_user1_idx` (`iduser` ASC),
  PRIMARY KEY (`iduser`),
  CONSTRAINT `fk_ciudadano_observatorio1`
    FOREIGN KEY (`idobs`)
    REFERENCES `Observapp`.`observatorio` (`idobservatorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ciudadano_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`comentario` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `texto` MEDIUMTEXT NULL,
  `fecha` DATETIME DEFAULT userCURRENT_TIMESTAMP,
  `iduser` INT(11) NOT NULL,
  `idpost` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_comentario_user1_idx` (`iduser` ASC),
  INDEX `fk_comentario_post1_idx` (`idpost` ASC),
  CONSTRAINT `fk_comentario_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `Observapp`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`megusta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`megusta` (
  `iduser` INT(11) NOT NULL,
  `idpost` INT UNSIGNED NOT NULL,
  INDEX `fk_megusta_user1_idx` (`iduser` ASC),
  INDEX `fk_megusta_post1_idx` (`idpost` ASC),
  PRIMARY KEY (`iduser`, `idpost`),
  CONSTRAINT `fk_megusta_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_megusta_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `Observapp`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`tags` (
  `idtag` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idtag`),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`tagpost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`tagpost` (
  `idtag` INT NOT NULL,
  `idpost` INT UNSIGNED NOT NULL,
  INDEX `fk_tagpost_tags1_idx` (`idtag` ASC),
  INDEX `fk_tagpost_post1_idx` (`idpost` ASC),
  PRIMARY KEY (`idtag`, `idpost`),
  CONSTRAINT `fk_tagpost_tags1`
    FOREIGN KEY (`idtag`)
    REFERENCES `Observapp`.`tags` (`idtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tagpost_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `Observapp`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `admin` (
  `idadmin` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(15),
  `apellido` VARCHAR(15),
  PRIMARY KEY (`idadmin`)
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
