-- MySQL Script generated by MySQL Workbench
-- 08/18/17 21:01:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Observapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Observapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Observapp` DEFAULT CHARACTER SET utf8 ;
USE `Observapp` ;

-- -----------------------------------------------------
-- Table `Observapp`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`institucion` (
  `idinstitucion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(80) NOT NULL,
  `correo` VARCHAR(40) NOT NULL,
  `fono` VARCHAR(12) NOT NULL,
  `comuna` VARCHAR(45) NULL,
  `avatar_pat` MEDIUMTEXT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idinstitucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `username` VARCHAR(10) NULL,
  `tipo` INT(1) UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fnac` DATE NULL,
  `gender` VARCHAR(1) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`evento` (
  `idevento` INT NOT NULL,
  `etapas` INT NULL,
  `likes` INT NULL,
  `nuevos` INT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idevento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`observatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`observatorio` (
  `idobservatorio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idinst` INT UNSIGNED NOT NULL,
  `idmonitor` INT(11) NOT NULL,
  `max` INT NOT NULL,
  `avatar_pat` MEDIUMTEXT NULL,
  `nom` VARCHAR(45) NULL,
  `fecha` DATETIME GENERATED ALWAYS AS (CURRENT_TIMESTAMP) VIRTUAL,
  `estado` INT NOT NULL DEFAULT 1,
  `idevento` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idobservatorio`),
  UNIQUE INDEX `idobservatorio_UNIQUE` (`idobservatorio` ASC),
  INDEX `fk_observatorio_institucion_idx` (`idinst` ASC),
  INDEX `fk_observatorio_user1_idx` (`idmonitor` ASC),
  INDEX `fk_observatorio_evento1_idx` (`idevento` ASC),
  CONSTRAINT `fk_observatorio_institucion`
    FOREIGN KEY (`idinst`)
    REFERENCES `Observapp`.`institucion` (`idinstitucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observatorio_user1`
    FOREIGN KEY (`idmonitor`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observatorio_evento1`
    FOREIGN KEY (`idevento`)
    REFERENCES `Observapp`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`post` (
  `idpost` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME GENERATED ALWAYS AS (CURRENT_TIMESTAMP) VIRTUAL,
  `iduser` INT(11) NOT NULL,
  `tipo` INT UNSIGNED NOT NULL,
  `t_principal` VARCHAR(300) NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  `contenido` MEDIUMTEXT NULL,
  `tags` VARCHAR(320) NULL,
  INDEX `fk_post_user1_idx` (`iduser` ASC),
  PRIMARY KEY (`idpost`),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`ciudadano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`ciudadano` (
  `idobs` INT UNSIGNED NOT NULL,
  `iduser` INT(11) NOT NULL,
  INDEX `fk_ciudadano_observatorio1_idx` (`idobs` ASC),
  INDEX `fk_ciudadano_user1_idx` (`iduser` ASC),
  PRIMARY KEY (`iduser`),
  CONSTRAINT `fk_ciudadano_observatorio1`
    FOREIGN KEY (`idobs`)
    REFERENCES `Observapp`.`observatorio` (`idobservatorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ciudadano_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`comentario` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `texto` MEDIUMTEXT NULL,
  `fecha` DATETIME GENERATED ALWAYS AS (CURRENT_TIMESTAMP) VIRTUAL,
  `iduser` INT(11) NOT NULL,
  `idpost` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_comentario_user1_idx` (`iduser` ASC),
  INDEX `fk_comentario_post1_idx` (`idpost` ASC),
  CONSTRAINT `fk_comentario_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `Observapp`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`megusta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`megusta` (
  `iduser` INT(11) NOT NULL,
  `idpost` INT UNSIGNED NOT NULL,
  INDEX `fk_megusta_user1_idx` (`iduser` ASC),
  INDEX `fk_megusta_post1_idx` (`idpost` ASC),
  PRIMARY KEY (`iduser`, `idpost`),
  CONSTRAINT `fk_megusta_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_megusta_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `Observapp`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`tags` (
  `idtag` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(30) NOT NULL,
  `tipo` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idtag`),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`tagpost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`tagpost` (
  `idtag` INT NOT NULL,
  `idpost` INT UNSIGNED NOT NULL,
  INDEX `fk_tagpost_tags1_idx` (`idtag` ASC),
  INDEX `fk_tagpost_post1_idx` (`idpost` ASC),
  PRIMARY KEY (`idtag`, `idpost`),
  CONSTRAINT `fk_tagpost_tags1`
    FOREIGN KEY (`idtag`)
    REFERENCES `Observapp`.`tags` (`idtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tagpost_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `Observapp`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`proyecto` (
  `idproyecto` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descripcion` MEDIUMTEXT NULL,
  `problema` VARCHAR(140) NULL,
  `etapa` INT NOT NULL DEFAULT 1,
  `idevento` INT NOT NULL,
  `creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idcreador` INT(11) NOT NULL,
  `media` VARCHAR(500) NOT NULL DEFAULT 'no',
  PRIMARY KEY (`idproyecto`),
  INDEX `fk_proyecto_evento1_idx` (`idevento` ASC),
  INDEX `fk_proyecto_user1_idx` (`idcreador` ASC),
  CONSTRAINT `fk_proyecto_evento1`
    FOREIGN KEY (`idevento`)
    REFERENCES `Observapp`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_user1`
    FOREIGN KEY (`idcreador`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`solucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`solucion` (
  `idsolucion` INT NOT NULL,
  `idproyecto` INT NOT NULL,
  `iduser` INT(11) NOT NULL,
  `contenido` MEDIUMTEXT NULL,
  `etapa` INT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` INT NULL,
  PRIMARY KEY (`idsolucion`),
  INDEX `fk_solucion_proyecto1_idx` (`idproyecto` ASC),
  INDEX `fk_solucion_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_solucion_proyecto1`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `Observapp`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solucion_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`userproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`userproyecto` (
  `iduser` INT(11) NOT NULL,
  `idproyecto` INT NOT NULL,
  `etapa` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`iduser`, `idproyecto`),
  INDEX `fk_user_has_proyecto_proyecto1_idx` (`idproyecto` ASC),
  INDEX `fk_user_has_proyecto_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_user_has_proyecto_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_proyecto_proyecto1`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `Observapp`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`actualizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`actualizacion` (
  `idactualizacion` INT NOT NULL,
  `tipo` INT NULL,
  `idproyecto` INT NOT NULL,
  `iduser` INT(11) NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `contenido` MEDIUMTEXT NULL,
  `principal` VARCHAR(500) NULL,
  PRIMARY KEY (`idactualizacion`),
  INDEX `fk_actualizacion_proyecto1_idx` (`idproyecto` ASC),
  INDEX `fk_actualizacion_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_actualizacion_proyecto1`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `Observapp`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actualizacion_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Observapp`.`tagproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`tagproyecto` (
  `idproyecto` INT NOT NULL,
  `idtag` INT NOT NULL,
  PRIMARY KEY (`idproyecto`, `idtag`),
  INDEX `fk_proyecto_has_tags_tags1_idx` (`idtag` ASC),
  INDEX `fk_proyecto_has_tags_proyecto1_idx` (`idproyecto` ASC),
  CONSTRAINT `fk_proyecto_has_tags_proyecto1`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `Observapp`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_has_tags_tags1`
    FOREIGN KEY (`idtag`)
    REFERENCES `Observapp`.`tags` (`idtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
