-- MySQL Script generated by MySQL Workbench
-- 11/21/17 17:41:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Observapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Observapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Observapp` DEFAULT CHARACTER SET latin1 ;
USE `Observapp` ;

-- -----------------------------------------------------
-- Table `Observapp`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`evento` (
  `idevento` INT(11) NOT NULL AUTO_INCREMENT,
  `etapas` INT(11) NULL DEFAULT NULL,
  `likes` INT(11) NULL DEFAULT NULL,
  `nuevos` INT(11) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idevento`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`institucion` (
  `idinstitucion` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(80) NOT NULL,
  `correo` VARCHAR(40) NOT NULL,
  `fono` VARCHAR(12) NOT NULL,
  `comuna` VARCHAR(45) NULL DEFAULT NULL,
  `avatar_pat` MEDIUMTEXT NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idinstitucion`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `username` VARCHAR(20) NULL DEFAULT NULL,
  `tipo` INT(1) UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `fnac` DATE NULL DEFAULT NULL,
  `gender` VARCHAR(1) NULL DEFAULT NULL,
  `avatar_pat` VARCHAR(300) NULL DEFAULT NULL,
  `comuna` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`observatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`observatorio` (
  `idobservatorio` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idinst` INT(10) UNSIGNED NOT NULL,
  `idmonitor` INT(11) NOT NULL,
  `max` INT(11) NOT NULL,
  `avatar_pat` MEDIUMTEXT NULL DEFAULT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` INT(11) NOT NULL DEFAULT '1',
  `idevento` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idobservatorio`),
  UNIQUE INDEX `idobservatorio_UNIQUE` (`idobservatorio` ASC),
  INDEX `fk_observatorio_institucion_idx` (`idinst` ASC),
  INDEX `fk_observatorio_user1_idx` (`idmonitor` ASC),
  INDEX `fk_observatorio_evento1` (`idevento` ASC),
  CONSTRAINT `fk_observatorio_evento1`
    FOREIGN KEY (`idevento`)
    REFERENCES `Observapp`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observatorio_institucion`
    FOREIGN KEY (`idinst`)
    REFERENCES `Observapp`.`institucion` (`idinstitucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observatorio_user1`
    FOREIGN KEY (`idmonitor`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`proyecto` (
  `idproyecto` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` MEDIUMTEXT NULL DEFAULT NULL,
  `problema` VARCHAR(140) NULL DEFAULT NULL,
  `etapa` INT(11) NOT NULL DEFAULT '1',
  `creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idcreador` INT(11) NOT NULL,
  `media` VARCHAR(500) NOT NULL DEFAULT 'no',
  `idevento` INT(11) NOT NULL DEFAULT '1',
  `gotlaik` INT(1) NOT NULL DEFAULT '0',
  `gotuser` INT(1) NOT NULL DEFAULT '0',
  `idobservatorio` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`idproyecto`),
  INDEX `fk_proyecto_user1_idx` (`idcreador` ASC),
  INDEX `fk_proyecto_evento1_idx` (`idevento` ASC),
  INDEX `fk_proyecto_obs` (`idobservatorio` ASC),
  CONSTRAINT `fk_proyecto_evento1`
    FOREIGN KEY (`idevento`)
    REFERENCES `Observapp`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_obs1`
    FOREIGN KEY (`idobservatorio`)
    REFERENCES `Observapp`.`observatorio` (`idobservatorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_user1`
    FOREIGN KEY (`idcreador`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`actualizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`actualizacion` (
  `idactualizacion` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` INT(11) NULL DEFAULT NULL,
  `idproyecto` INT(11) NOT NULL,
  `iduser` INT(11) NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `contenido` MEDIUMTEXT NULL DEFAULT NULL,
  `principal` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`idactualizacion`),
  INDEX `fk_actualizacion_proyecto1_idx` (`idproyecto` ASC),
  INDEX `fk_actualizacion_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_actualizacion_proyecto1`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `Observapp`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actualizacion_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`admin` (
  `idadmin` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(15) NULL DEFAULT NULL,
  `apellido` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`ciudadano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`ciudadano` (
  `idobs` INT(10) UNSIGNED NOT NULL,
  `iduser` INT(11) NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_ciudadano_observatorio1_idx` (`idobs` ASC),
  INDEX `fk_ciudadano_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_ciudadano_observatorio1`
    FOREIGN KEY (`idobs`)
    REFERENCES `Observapp`.`observatorio` (`idobservatorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ciudadano_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`post` (
  `idpost` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `iduser` INT(11) NOT NULL,
  `tipo` INT(10) UNSIGNED NOT NULL,
  `t_principal` VARCHAR(300) NOT NULL,
  `estado` INT(11) NOT NULL DEFAULT '1',
  `contenido` MEDIUMTEXT NULL DEFAULT NULL,
  `tags` VARCHAR(320) NULL DEFAULT NULL,
  `idobs` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`idpost`),
  INDEX `fk_post_user1_idx` (`iduser` ASC),
  INDEX `fk_post_obs1_idx` (`idobs` ASC),
  CONSTRAINT `fk_post_obs1`
    FOREIGN KEY (`idobs`)
    REFERENCES `Observapp`.`observatorio` (`idobservatorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`comentario` (
  `idcomentario` INT(11) NOT NULL AUTO_INCREMENT,
  `texto` MEDIUMTEXT NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `iduser` INT(11) NOT NULL,
  `idpost` INT(10) UNSIGNED NOT NULL,
  `estado` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_comentario_user1_idx` (`iduser` ASC),
  INDEX `fk_comentario_post1_idx` (`idpost` ASC),
  CONSTRAINT `fk_comentario_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `Observapp`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`postinterno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`postinterno` (
  `idpostinterno` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` INT(11) NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `laiks` VARCHAR(100) NULL DEFAULT NULL,
  `idproyecto` INT(11) NOT NULL,
  `texto1` MEDIUMTEXT NULL DEFAULT NULL,
  `texto2` MEDIUMTEXT NULL DEFAULT NULL,
  `token` VARCHAR(200) NULL DEFAULT NULL,
  `iduser` INT(11) NOT NULL,
  PRIMARY KEY (`idpostinterno`),
  INDEX `fk_postinterno_proyecto1_idx` (`idproyecto` ASC),
  INDEX `fk_postinterno_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_postinterno_proyecto1`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `Observapp`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postinterno_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`comentinterno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`comentinterno` (
  `idcomentinterno` INT(11) NOT NULL AUTO_INCREMENT,
  `texto` MEDIUMTEXT NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idpost` INT(11) NOT NULL,
  `iduser` INT(11) NOT NULL,
  PRIMARY KEY (`idcomentinterno`),
  INDEX `fk_comentinterno_postinterno1_idx` (`idpost` ASC),
  INDEX `fk_comentinterno_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_comentinterno_postinterno1`
    FOREIGN KEY (`idpost`)
    REFERENCES `Observapp`.`postinterno` (`idpostinterno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentinterno_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`etapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`etapa` (
  `idetapa` INT(11) NOT NULL AUTO_INCREMENT,
  `token` MEDIUMTEXT NULL DEFAULT NULL,
  `nro` INT(11) NOT NULL,
  `idevento` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idetapa`),
  INDEX `fk_etapa_evento1_idx` (`idevento` ASC),
  CONSTRAINT `fk_etapa_evento1`
    FOREIGN KEY (`idevento`)
    REFERENCES `Observapp`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`megusta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`megusta` (
  `iduser` INT(11) NOT NULL,
  `idpost` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`iduser`, `idpost`),
  INDEX `fk_megusta_user1_idx` (`iduser` ASC),
  INDEX `fk_megusta_post1_idx` (`idpost` ASC),
  CONSTRAINT `fk_megusta_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `Observapp`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_megusta_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`proylike`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`proylike` (
  `iduser` INT(11) NOT NULL,
  `idproyecto` INT(11) NOT NULL,
  PRIMARY KEY (`iduser`, `idproyecto`),
  INDEX `fk_user_has_proyecto_proyecto2_idx` (`idproyecto` ASC),
  INDEX `fk_user_has_proyecto_user2_idx` (`iduser` ASC),
  CONSTRAINT `fk_user_has_proyecto_proyecto2`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `Observapp`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_proyecto_user2`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`solucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`solucion` (
  `idsolucion` INT(11) NOT NULL AUTO_INCREMENT,
  `idproyecto` INT(11) NOT NULL,
  `iduser` INT(11) NOT NULL,
  `contenido` MEDIUMTEXT NULL DEFAULT NULL,
  `etapa` INT(11) NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idsolucion`),
  INDEX `fk_solucion_proyecto1_idx` (`idproyecto` ASC),
  INDEX `fk_solucion_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_solucion_proyecto1`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `Observapp`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solucion_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`tags` (
  `tag` VARCHAR(50) NOT NULL,
  `idtag` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idtag`),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 124
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`tagpost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`tagpost` (
  `idtag` INT(11) NOT NULL,
  `idpost` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idtag`, `idpost`),
  INDEX `fk_tagpost_tags1_idx` (`idtag` ASC),
  INDEX `fk_tagpost_post1_idx` (`idpost` ASC),
  CONSTRAINT `fk_tagpost_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `Observapp`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tagpost_tags1`
    FOREIGN KEY (`idtag`)
    REFERENCES `Observapp`.`tags` (`idtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`tagproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`tagproyecto` (
  `idproyecto` INT(11) NOT NULL,
  `idtag` INT(11) NOT NULL,
  PRIMARY KEY (`idproyecto`, `idtag`),
  INDEX `fk_proyecto_has_tags_tags1_idx` (`idtag` ASC),
  INDEX `fk_proyecto_has_tags_proyecto1_idx` (`idproyecto` ASC),
  CONSTRAINT `fk_proyecto_has_tags_proyecto1`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `Observapp`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_has_tags_tags1`
    FOREIGN KEY (`idtag`)
    REFERENCES `Observapp`.`tags` (`idtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Observapp`.`userproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Observapp`.`userproyecto` (
  `iduser` INT(11) NOT NULL,
  `idproyecto` INT(11) NOT NULL,
  `etapa` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`iduser`, `idproyecto`),
  INDEX `fk_user_has_proyecto_proyecto1_idx` (`idproyecto` ASC),
  INDEX `fk_user_has_proyecto_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_user_has_proyecto_proyecto1`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `Observapp`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_proyecto_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Observapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
